<?php
// $Id$

/**
 * @file
 * Configuration interface to provide a quick and easy way of replacing text.
 */

/**
 * Implementation of hook_help()
 */
function stringoverrides_help($path, $arg) {
  $output = '';
  if ($path == 'admin/help#stringoverrides') {
    $output = '<p>'.  t('The String Overrides module provides a quick and easy way of replacing text.') .'</p>';
  }
  else if($arg[0] == 'admin' && $arg[1] == 'settings' && $arg[2] == 'stringoverrides') {
    $output = '<p>'.  t("The following provides quick and easy way of replacing text.") .'</p>';
  }
  return $output;
} // function stringoverrides_help

/**
 * Implementation of hook_menu()
 */
function stringoverrides_menu() {
  $items = array();
  $items['admin/settings/stringoverrides'] = array(
    'title' => 'String overrides',
    'description' => 'Provides a quick and easy way of replacing text on the site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stringoverrides_admin', 3),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'stringoverrides.admin.inc',
  );
  
  // Add the language tabs if there are other languages
  if (module_exists('locale')) {
    global $language;
    $languages = locale_language_list();
    foreach($languages as $code => $name) {
      $items["admin/settings/stringoverrides/$code"] = array(
        'title' => $name,
        'page arguments' => array('stringoverrides_admin', $code),
        'type' => $language->language == $code ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK,
      );
    }
  }
  
  $items['admin/settings/stringoverrides/js'] = array(
    'title' => 'String Overrides Javascript',
    'page callback' => 'stringoverrides_js',
    'type' => MENU_CALLBACK,
    'file' => 'stringoverrides.admin.inc',
  );
  return $items;
} // function stringoverrides_menu

/**
 * Implementation of hook_theme()
 */
function stringoverrides_theme() {
  return array(
    'stringoverrides_strings' => array(
      'arguments' => array('form' => NULL),
    ),
  );
} // function stringoverrides_theme
